
declare class MLKDigitalInkRecognitionCandidate extends NSObject {

	static alloc(): MLKDigitalInkRecognitionCandidate; // inherited from NSObject

	static new(): MLKDigitalInkRecognitionCandidate; // inherited from NSObject

	readonly score: number;

	readonly text: string;
}

declare class MLKDigitalInkRecognitionContext extends NSObject {

	static alloc(): MLKDigitalInkRecognitionContext; // inherited from NSObject

	static new(): MLKDigitalInkRecognitionContext; // inherited from NSObject

	readonly preContext: string;

	readonly writingArea: MLKWritingArea;

	constructor(o: { preContext: string; writingArea: MLKWritingArea; });

	initWithPreContextWritingArea(preContext: string, writingArea: MLKWritingArea): this;
}

declare class MLKDigitalInkRecognitionModel extends MLKRemoteModel {

	static alloc(): MLKDigitalInkRecognitionModel; // inherited from NSObject

	static new(): MLKDigitalInkRecognitionModel; // inherited from NSObject

	readonly modelIdentifier: MLKDigitalInkRecognitionModelIdentifier;

	constructor(o: { modelIdentifier: MLKDigitalInkRecognitionModelIdentifier; });

	initWithModelIdentifier(modelIdentifier: MLKDigitalInkRecognitionModelIdentifier): this;
}

declare class MLKDigitalInkRecognitionModelIdentifier extends NSObject {

	static allModelIdentifiers(): NSSet<MLKDigitalInkRecognitionModelIdentifier>;

	static alloc(): MLKDigitalInkRecognitionModelIdentifier; // inherited from NSObject

	static modelIdentifierForLanguageTag(languageTag: string): MLKDigitalInkRecognitionModelIdentifier;

	static modelIdentifierFromLanguageTagError(languageTag: string): MLKDigitalInkRecognitionModelIdentifier;

	static modelIdentifiersForLanguageSubtag(languageSubtag: string): NSSet<MLKDigitalInkRecognitionModelIdentifier>;

	static modelIdentifiersForRegionSubtag(regionSubtag: string): NSSet<MLKDigitalInkRecognitionModelIdentifier>;

	static modelIdentifiersForScriptSubtag(scriptSubtag: string): NSSet<MLKDigitalInkRecognitionModelIdentifier>;

	static new(): MLKDigitalInkRecognitionModelIdentifier; // inherited from NSObject

	readonly languageSubtag: string;

	readonly languageTag: string;

	readonly regionSubtag: string;

	readonly scriptSubtag: string;
}

declare var MLKDigitalInkRecognitionModelIdentifierAaLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierAbsLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierAceLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierActLatnNl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierAf: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierAm: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierAnLatnEs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierAnwLatnNg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierAr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierAs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierAutodraw: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierAwaDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierAzLatnAz: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBahLatnBs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBarLatnAt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBcqLatnEt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBerLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBewLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBfyDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBfzDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBgcDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBgqDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBgqDevaPk: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBgxLatnTr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBgzLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBhbDeva: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBhoDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBiLatnVu: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBikLatnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBjjDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBjnLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBnLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBoTibt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBomLatnNg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBrxDeva: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBrxLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBtoLatnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBtzLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierBzcLatnMg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierCa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierCebLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierCggLatnUg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierChGu: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierCjkLatnCd: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierCoLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierCpsLatnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierCrsLatnSc: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierCs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierCy: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierCyoLatnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDeAt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDeBe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDeCh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDeDe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDeLu: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDnjLatnCi: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDoiDeva: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDoiLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDrsLatnEt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDrtLatnNl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierDsbDe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEmoji: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEnAu: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEnCa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEnGb: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEnIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEnKe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEnNg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEnUs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEnZa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEo: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEsAr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEsEs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEsMx: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEsUs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEtEe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEu: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierEuEs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierExtLatnEs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFanLatnGq: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFi: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFilLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFjFj: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFoFo: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFr002: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFrBe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFrCa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFrCh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFrFr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierFy: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGaxLatnEt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGayLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGbmDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGcrLatnGf: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGdLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGdLatnGb: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGdxDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGjuDeva: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGlEs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGosLatnNl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGpeLatnGh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGswCh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGu: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGuLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGv: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierGynLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHaqLatnTz: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHawLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHdyLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHi: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHiLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHifDeva: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHilLatnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHmnLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHneDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHniLatnCn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHoLatnPg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHojDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHrxLatnBr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHu: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierHy: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierIgbLatnNg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierIiLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierIloLatnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierIs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierIt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierItCh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierItIt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierIumLatnCn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierJa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierJamLatnJm: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierJaxLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierJboLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierJvLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKdeLatnTz: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKfrDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKfyDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKgeLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKhaLatnIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKjLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKk: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKm: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKmbLatnAo: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKmzLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKnLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKo: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKok: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKokIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKokLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKruDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKsDeva: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKsLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKshLatnDe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKtbLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKtuLatnCd: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKuLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKwLatnGb: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierKyCyrl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLadLatnBa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLajLatnUg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLb: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLedLatnCd: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLldLatnIt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLmnDeva: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLo: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLonLatnMw: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLuyLatnKe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierLv: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMadLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMagDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMaiIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMaiLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMasLatnKe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMaxLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMdhLatnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMelLatnMy: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMeoLatnMy: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMfbLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMfpLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMiLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMinLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMk: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMlLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMnCyrl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMniLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMqyLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMrIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMrLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMrwLatnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMsBn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMsMy: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMsiLatnMy: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMtrDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMuiLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMupDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMveDevaPk: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMwrDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMwwLatnCn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMy: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierMyxLatnUg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNahLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNapLatnIt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNdcLatnZw: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNeIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNeLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNeNp: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNewDevaNp: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNgLatnNa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNgaLatnCd: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNiqLatnKe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNlBe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNlNl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNnNo: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNo: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNoeDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNrZa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNso: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNy: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNymLatnTz: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierNyoLatnUg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierOcLatnFr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierOjLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierOloLatnRu: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierOm: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierOr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierOrLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPaLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPagLatnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPamLatnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPapLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPccLatnCn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPcdLatnBe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPcmLatnNg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPkoLatnKe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPmsLatnIt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPmyLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPovLatnGw: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPrkLatnMm: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPseLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPt002: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPtBr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierPtPt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierQuPe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierQucLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierRcfLatnRe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierRktDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierRmCh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierRnBi: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierRoRo: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierRu: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierRwrDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSaDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSaLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSatDeva: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSatLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierScLatnIt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSckDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierScoLatnGb: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSdDeva: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSdLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSdcLatnIt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSgCf: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSgcLatnKe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSgjDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSgsLatnLt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierShapes: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSi: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSk: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSkgLatnMg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSm: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSnLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSo: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSq: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSrCyrl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSrLatnRs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSsSz: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierStvLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSuLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSukLatnTz: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSvFi: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSvSe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSw: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSwvDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSxuLatnDe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierSylLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTa: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTaLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTdxLatnMg: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTeLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTetLatnTl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTgCyrl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTi: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTkLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTnBw: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTpi: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTrTr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTrfLatnTt: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTrpLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTs: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTsgLatnPh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTumLatnMw: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTuvLatnKe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierTwdLatnNl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierUk: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierUnrDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierUnrLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierUr: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierUrLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierUrPk: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierUzLatn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierVelLatnNl: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierVepLatnRu: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierVi: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierVktLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierWaLatnBe: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierWbrDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierWryDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierXh: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierXmmLatnId: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierXnrDevaIn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierYmmLatnSo: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierZaLatnCn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierZhHani: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierZhHaniCn: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierZhHaniHk: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierZhHaniTw: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierZu: MLKDigitalInkRecognitionModelIdentifier;

declare var MLKDigitalInkRecognitionModelIdentifierZyjLatnCn: MLKDigitalInkRecognitionModelIdentifier;

declare class MLKDigitalInkRecognitionResult extends NSObject {

	static alloc(): MLKDigitalInkRecognitionResult; // inherited from NSObject

	static new(): MLKDigitalInkRecognitionResult; // inherited from NSObject

	readonly candidates: NSArray<MLKDigitalInkRecognitionCandidate>;
}

declare class MLKDigitalInkRecognizer extends NSObject {

	static alloc(): MLKDigitalInkRecognizer; // inherited from NSObject

	static digitalInkRecognizerWithOptions(options: MLKDigitalInkRecognizerOptions): MLKDigitalInkRecognizer;

	static new(): MLKDigitalInkRecognizer; // inherited from NSObject

	recognizeInkCompletion(ink: MLKInk, completion: (p1: MLKDigitalInkRecognitionResult, p2: NSError) => void): void;

	recognizeInkContextCompletion(ink: MLKInk, context: MLKDigitalInkRecognitionContext, completion: (p1: MLKDigitalInkRecognitionResult, p2: NSError) => void): void;
}

declare class MLKDigitalInkRecognizerOptions extends NSObject {

	static alloc(): MLKDigitalInkRecognizerOptions; // inherited from NSObject

	static new(): MLKDigitalInkRecognizerOptions; // inherited from NSObject

	maxResultCount: number;

	readonly model: MLKDigitalInkRecognitionModel;

	constructor(o: { model: MLKDigitalInkRecognitionModel; });

	initWithModel(model: MLKDigitalInkRecognitionModel): this;
}

declare class MLKInk extends NSObject {

	static alloc(): MLKInk; // inherited from NSObject

	static new(): MLKInk; // inherited from NSObject

	readonly strokes: NSArray<MLKStroke>;

	constructor(o: { strokes: NSArray<MLKStroke> | MLKStroke[]; });

	initWithStrokes(strokes: NSArray<MLKStroke> | MLKStroke[]): this;
}

declare class MLKStroke extends NSObject {

	static alloc(): MLKStroke; // inherited from NSObject

	static new(): MLKStroke; // inherited from NSObject

	readonly points: NSArray<MLKStrokePoint>;

	constructor(o: { points: NSArray<MLKStrokePoint> | MLKStrokePoint[]; });

	initWithPoints(points: NSArray<MLKStrokePoint> | MLKStrokePoint[]): this;
}

declare class MLKStrokePoint extends NSObject {

	static alloc(): MLKStrokePoint; // inherited from NSObject

	static new(): MLKStrokePoint; // inherited from NSObject

	readonly t: number;

	readonly x: number;

	readonly y: number;

	constructor(o: { x: number; y: number; });

	constructor(o: { x: number; y: number; t: number; });

	initWithXY(x: number, y: number): this;

	initWithXYT(x: number, y: number, t: number): this;
}

declare class MLKWritingArea extends NSObject {

	static alloc(): MLKWritingArea; // inherited from NSObject

	static new(): MLKWritingArea; // inherited from NSObject

	readonly height: number;

	readonly width: number;

	constructor(o: { width: number; height: number; });

	initWithWidthHeight(width: number, height: number): this;
}
